name: eValor

readme:

    tags: >
        evalor, sidebar, review, reviews, woocommerce, tienda online, sello,
        opinion, valoracion, review, reviews

    intro: >
        Este módulo integra el sidebar de eValor con su web WordPress o su
        tienda WooCommerce.

    description: >
        El módulo WordPress facilita la integración del innovador sidebar de
        evalor en su web WordPress o tienda WooCommerce.  Para los usuarios del
        WooCommerce Plugin para WordPress el módulo se encarga de invitar de
        forma automática a los clientes para que compartan su experiencia. Esta
        funcion solo esta disponible para clientes PLUS.  Cuando el proceso del
        pedido ha finalizado se envia automaticamente una invitacion al cliente
        para que comparta su experiencia. Asi se genera confianza y aumenta la
        conversion de su tienda online.

    installation: >
        1. Introduzca la carpeta "eValor" en la carpeta "wp-content/plugins" en
        el servidor web.

        1. A continuacion podra activar el plugin en el panel de control. Vaya a
        plugins y haga click en activar en el plugin de eValor.

        1. Despues entre en configuraciones para configurar el plugin.

        1. Para finalizar compruebe si aparece el sidebar en su web.
