name: WebwinkelKeur

readme:

    tags: |
        webwinkelkeur, sidebar, review, reviews, woocommerce, webwinkel, keur, keurmerk, waardering

    intro: |
        Deze module integreert de WebwinkelKeur sidebar in uw WordPress website of WooCommerce webshop.

    description: |
        De WordPress module zorgt voor een eenvoudige integratie van het WebwinkelKeur binnen jouw WordPress website en WooCommerce webwinkel. Zo integreert de module automatisch de innovatieve [WebwinkelKeur Sidebar][1] binnen elke WordPress website of webwinkel.  Voor gebruikers van de WooCommerce plugin voor WordPress zorgt de module voor het automatisch uitnodigen van klanten voor het delen van een klantervaring. Deze functie is alleen beschikbaar voor PLUS leden.  Bij elke afgewerkte bestelling wordt automatisch een uitnodiging naar de klant verzonden waarin hij uitgenodigd wordt om zijn ervaring te delen. Zo vergroot je het vertrouwen en de conversie van jouw webwinkel.

        [Klik hier][2] voor meer informatie over de WordPress module.

        [1]: https://www.webwinkelkeur.nl/webwinkel/mogelijkheden/sidebar/
        [2]: https://www.webwinkelkeur.nl/webwinkel/mogelijkheden/wordpress-module/

    installation: |
        1. Plaats de map "webwinkelkeur" in de map "wp-content/plugins" op de webserver.
        1. De plugin kan nu worden geactiveerd in de administratieinterface. Ga daarvoor naar Plugins en klik op Activeren bij de WebwinkelKeur plugin.
        1. Klik op Instellingen om de plugin te configureren.
        1. Controleer of de sidebar op uw site wordt getoond.

    faq: |
        = Kan ik voorkomen dat voor bepaalde orders uitnodingen worden aangevraagd? =

        Dat kan door de hook `webwinkelkeur_request_invitation` te implementeren:

        ~~~
        add_filter('webwinkelkeur_request_invitation', function ($should_invite, WC_Order $order) {
            if ($order->get_total() < 10) {
                return false;
            }
            return $should_invite;
        }, 10, 2);
        ~~~
